In [1]:

import pandas as pd
import socket
import struct
import numpy as np

In [2]:
def convert_ipv4(addr):
    return struct.unpack("!I", socket.inet_aton(addr))[0]

def con_proto(proto):
    protos = ['icmp', 'tcp', 'udp']
    return protos.index(proto)

In [13]:
def norm_df(df, split_into=1):
    """
    param: split_into [this is a percentage, how much of the dataset should be used]
    """
    assert 0 < split_into <= 1, "Number must be percentage"
    df = df.replace('-', np.nan)
    df['orig_h'] = df['orig_h'].apply(convert_ipv4)
    df['resp_h'] = df['resp_h'].apply(convert_ipv4)
    # df = pd.get_dummies(df, columns=['proto'], dtype=int)
    df['proto'] = df['proto'].apply(con_proto)
    # print(dummies.head())
    df = df.drop(['service', 'duration', 'missed_bytes', 'history', 'uid', 'conn_state', 'local_orig', 'local_resp', 'orig_ip_bytes',
                 'resp_ip_bytes', 'orig_pkts', 'resp_pkts', 'detailed_label', 'ts', 'resp_bytes', 'orig_bytes', 'tunnel_parents'], axis=1)
    df['label'] = (df['label'] == "Malicious").astype(int)
    df = df.dropna()
    if (split_into):
        df = np.array_split(df.sample(frac=1), 1/split_into)[0]
    df = df.reset_index(drop=True)
    return df

In [14]:
def convert_to_csv(FILEID):
        NUMERIC_COLUMNS = ['ts', 'orig_p', 'resp_p', "orig_bytes", "resp_bytes", "missed_bytes", "orig_pkts", 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'duration'] # integer columns
        LOGFILE = f"~/Downloads/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-{FILEID}-1/bro/conn.log.labeled"
        fieldsIN = ['ts', 'uid', 'orig_h', 'orig_p', 'resp_h', 'resp_p', 'proto', 'service', 'duration', 'orig_bytes', 'resp_bytes', 'conn_state',
                'local_orig', 'local_resp', 'missed_bytes', 'history', 'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'tunnel_parents', 'label', 'detailed_label']
        df = pd.read_csv(LOGFILE, sep="\x09|\x20\x20\x20", skiprows=10, skipfooter=2,
                        names=fieldsIN, header=None, engine='python')
        df = norm_df(df)
        df.to_csv(f'csv/capture{FILEID}_1.csv')
        return df

In [15]:
convert_to_csv(1)

orig_h 0
orig_p 0
resp_h 0
resp_p 0
proto 0
label 0

             orig_h  orig_p      resp_h  resp_p  proto  label
0        3232261223   50627   238428813      23      1      1
1        3232261223   43763  2396638396   11065      2      0
2        3232261223   40584  3542525043      23      1      1
3        3232261223   59334   331139160    2323      1      1
4        3232261223   49700  3684511560      23      1      1
...             ...     ...         ...     ...    ...    ...
1008740  3232261223   40901  1107803976   33730      1      0
1008741  3232261223   43763  3709707613   46237      2      0
1008742  3232261223   43763   681990666   41427      2      0
1008743  3232261223   43763  4145340020   46248      2      0
1008744  3232261223   60569   579886208    2270      1      0

[1008745 rows x 6 columns]